version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shorttyUrls_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: shorttyUrlDB
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: shorttypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
